### ISSUE TITLE
Damage cause is fall Bug

### ISSUE THREAD

**Issue by Adondriel** [Njol/Skript#246]
Using this skript:
# 
# No dmg on hay
# 

on damage:
    damage cause is fall
    block below victim is hay block
    cancel event

It works, most of the time. But my users are still taking damage when they fall for too long. So like, they can fall from a short building or house, and it works perfectly, but when they fall from a fairly tall building, they still take the damage i am really not sure why this is happening.

**Comment by Njol** [comment]
I guess that the player is either in the block they'll land on, or they are not yet near the block they'll land on because their speed is higher than 20 blocks per second. Add a 'message "%block at player%"' to the script and try falling from a high place to find out which one is the case and then try to modify your script accordingly.

PS: I won't add a workaround to Skript as it would be extremely difficult to code and could cause issues with all sorts of effects.
