### ISSUE TITLE
[Bug?] entity type

### ISSUE THREAD

**Issue by Tsugaga** [Njol/Skript#267]
I can't parse most things as entity type or spawn most entities. cow, pig, sheep, zombie, etc are all invalid entity types. I remember them working before but now they don't. Skeleton, unsaddled pig, and unsheared sheep work though.

Working:
-spider
-creeper
-unsaddled pig
-unsheared sheep
-skeleton
-witch
-wither skeleton

Broken:
-pig
-cow
-sheep
-zombie
-chicken
-zombie pigman
-villager

Also after a server restart, any variable that was set as an entity type breaks and becomes "entity".

**Comment by Njol** [comment]
I modified the whole variable saving system for 2.1, and I successfully saved and loaded entity types without loosing any data. I also fixed sheep to be unsheared sheep all the time and related errors.
I was also able to spawn a pig without issues, so i guess that this issue will be fixed in the next version.

**Comment by Tsugaga** [comment]
Forgot to mention this is on a 1.4.7 server. cow, pig, chicken, zombie, and zombie pigman are invalid entity types. Also mooshroom entity type returns "cow".

**Comment by Njol** [comment]
I just tested "set {_s} to pig, cow, chicken, or zombie pigman" which doesn't result in an error for me. I'll still have to fix the Mooshroom though, it's arranged improperly at the moment.

**Comment by Tsugaga** [comment]
You have tested in on 1.4.7? Like I said my server is 1.4.7, mindcrack, with mcpc too.

**Comment by Tsugaga** [comment]
Ignore this issue, it can be closed.
