### ISSUE TITLE
effect to close any open GUI (if possible)

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#288]

**Comment by joeuguce99** [comment]
As far as I know, teleporting works well.

**Comment by ghost** [comment]
My issue. (I've posted as televisornull recently). Unfortunately, I had to write a bad fix for Applied Energistics mod which doesn't send packets to server when GUI is opened. So. all players were able to open machines of each other. I wrote like this:
[here is code for detecting if the opened inventory belongs to necessary block]:
    open ender chest of player to player
    teleport player to player
But if I write like this:
[here is code for detecting ... ]:
    teleport player to player
In this case inventory doesn't close at all. Because Applied Energistics uses its own packet receiving-sending system. It's awful. So I have to open ender chest at first (it closes inventory of buggy mechanism), then to close ender chest by teleporting player to himself. What a f*\* usage of Skript, don't you think so?
I vote for adding this function as soon as possible. It will close many bugs and dupes, you know. It should be like this:
[here is conditional]:
    close the inventory of player (or modded block, I don't know exactly how it works).
Hope you understand me. Big thanks for opening this issue! Yours, getsmp.

**Comment by ghost** [comment]
@Njol, any news about this feature?

**Comment by ghost** [comment]
Oh, done in 2.1.2, thanks! Issue should be closed.

**Comment by joshwenke** [comment]
http://njol.ch/projects/skript/doc/effects/#EffOpenInventory for reference to those who are interested
